"Source Plugin file
source ~/.vim_pluginrc

filetype plugin indent on

" General vim options
set number          "set line number
set relativenumber  "set relative line number
set tabstop=4       "show existing tab with 4 spaces width
set expandtab       "On pressing tab, insert 4 spaces
set cursorline      "Highlight the line on which the cursor is at present
set shiftwidth=4    "when indenting with '>', use 4 spaces width
set background=dark
set completeopt=menuone,noinsert "While showing autocomplete do not insert
set fillchars+=vert:│   "Set character for vertical split separator
"set foldmethod=indent
"set foldcolumn=3
hi VertSplit ctermbg=NONE guibg=NONE 
set tags=tags



let mapleader = "," "

"Auto Commands

" Skip quickfix window when moving across buffers
augroup qf
    autocmd!
    autocmd FileType qf set nobuflisted
augroup END

" General key remap

"Use < > keys to navigate buffers
nnoremap < :bprevious<CR> 
nnoremap > :bnext<CR>

"Filetype specific settings
autocmd FileType python,sh,markdown,vim  setlocal colorcolumn=80
autocmd ColorScheme * highlight VertSplit cterm=NONE ctermfg=green ctermbg=NONE


"Others
colorscheme solarized
syntax on
hi Terminal ctermbg=black ctermfg=blue guibg=lightgrey guifg=blue
