"Source Plugin file
source ~/.vim/.pluginrc

filetype plugin indent on

" General vim options
se nu               "set line number
se rnu              "set relive line number
set tabstop=4       "show existing tab with 4 spaces width
set expandtab       "On pressing tab, insert 4 spaces
set cursorline      "Highlight the line on which the cursor is at present
set shiftwidth=4    "when indenting with '>', use 4 spaces width
set background=dark
set completeopt=menuone,noinsert "While showing autocomplete do not insert
set fillchars+=vert:│   "Set character for vertical split separator
hi VertSplit ctermbg=NONE guibg=NONE 



let mapleader = "," "

"Auto Commands

" Skip quickfix window when moving across buffers
augroup qf
    autocmd!
    autocmd FileType qf set nobuflisted
augroup END

" General key remap

"Use < > keys to navigate buffers
nnoremap < :bp<CR>
nnoremap > :bn<CR>

"Filetype specific settings
autocmd FileType python,sh,vimwiki,vim  setlocal colorcolumn=80


"Others
colorscheme solarized
syntax on

