#!/usr/local/bin/zsh

SESSION_NAME="code"
REACT_WINDOW="react"
CSS_WINDOW="css"
NOTES_WINDOW="notes"

# Start New session with session name
tmux new-session -d -s ${SESSION_NAME}


# React window
tmux rename-window -t ${SESSION_NAME}:1 'react'
tmux send-keys -t ${REACT_WINDOW} 'zsh' C-m 'cd ~/src/reactjs/crwn-clothing/src' C-m 'vi' C-m

tmux split-window -t ${SESSION_NAME}
tmux send-keys -t 'react'.1 'cd ~/src/reactjs/crwn-clothing/' C-m 'yarn start' C-m

tmux new-window -n ${CSS_WINDOW}
tmux send-keys -t ${CSS_WINDOW}.0 'zsh' C-m 'cd ~/src/css/course/' C-m 'vi' C-m

tmux new-window -n ${NOTES_WINDOW}
tmux send-keys -t ${NOTES_WINDOW}.0 'zsh' C-m 'cd ~/notes/freedom' C-m  'vi' C-m

